### PR TITLE
spanish translations

### PR DESCRIPTION
**Pull request by sonic182**
Spanish translations added

### CODE REVIEW

**Comment by scambra** [comment]
translations are not provided on gem, as devise does, you can add them to wiki:
https://github.com/scambra/devise_invitable/wiki/I18n

**Comment by sonic182** [comment]
Mmmm then should exist something like: gem 'devise-invitable-i18n'
or should add https://github.com/scambra/devise_invitable/wiki/I18n link on readme on i18n section

**Comment by scambra** [comment]
I added link to readme

**Comment by sonic182** [comment]
Perfect!

2016-06-15 14:27 GMT+02:00 Sergio Cambra <notifications@github.com>:

**Pull request closed without merging**
