### PR TITLE
add 18n locale - es.yml

### PR DESCRIPTION
**Pull request by yshmarov**
I think it would be a nice addition to add more locales :)

### CODE REVIEW

**Comment by scambra** [comment]
We have locales in wiki, as devise does, I don't see the point in adding locales to devise invitable while devise doesn't have them.

**Comment by yshmarov** [comment]
@scambra but devise has the gem devise-18n that contains all the locales.

I would see no point in creating a gem devise-invitable-i18n, as an addition to an addition 😃.

Right now any developer working with i18n & devise-invitable has to go to the wiki and copypaste all the locales he needs. Not a perfect user experience..

If you accept, I can do the work of adding **all** the locales from wiki to `config`

**Comment by scambra** [comment]
@yshmarov I didn't know that gem, when I wrote devise invitable they only had locales in wiki. It would be great if you can send pull request with all locales from wiki then.

**Comment by yshmarov** [comment]
ok!

**Comment by yshmarov** [comment]
#834

**Pull request closed without merging**
