### PR TITLE
Update invitations_controller.rb

### PR DESCRIPTION
**Pull request by apoyan**
Sign out before accepting the invitation if the user logged in

### CODE REVIEW

**Comment by scambra** [comment]
You are right, it won't work. However I'm not sure now what's better default user experience, redirect with error message or sign out.

Without sign out, if someone wants its application to sign out before accept invitation, it's possible to create inherited controller, skip before_action and add sign out with before action.
If sign out is added, and require_no_authentication removed, sign out should be added with before_action so someone may inherit controller to remove sign out and add require_no_authentication.

Or maybe, it could be a DeviseInvitable setting.

**Comment by corinnekunze** [comment]
FYI @scambra I have an issue as well when devise is nested in a routing namespace like so:

```
namespace :admin do
  resources :users
end
```

In this case, `resource_name` from the devise.mapping will return `:admin_user` instead of `:user` so this line will not evaluate correctly:
```
sign_out send("current_#{resource_name}") if send("#{resource_name}_signed_in?")
```

My solution for our app was to call it in a custom extended controller like so:
```
def edit
  sign_out(current_user) if user_signed_in?
  super
end
```

**Comment by alyssais** [comment]
I do this in my controller like this, and it works well:

```ruby
prepend_before_action :sign_out, only: :edit
```

**Comment by crohr** [comment]
I agree with @Systho and @alyssais: this change is not required, and in our case it breaks the invitation flow since we allow a user to accept an invitation while being signed in, so that he can use his existing user account to join (in our case) organizations, instead of accepting the invitation as a new user (and thus creating another unnecessary user account).

**Pull request merged**
